# Basic Configuration
title: Koki Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Koki Blog は、テクノロジー、プログラミング、生活に関する個人ブログです。
baseurl: "/koki-labo"
url: "https://kokilabo.github.io"
repository: kokilabo/koki-labo

# Remote Theme Settings
plugins:
  - jekyll-remote-theme

remote_theme: poole/lanyon
