# Basic Configuration
title: Koki Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Koki Blog is a personal blog about technology, programming, and life.
baseurl: ""
url: ""
repository: kokilabo/koki-labo

# Remote Theme Settings
plugins:
  - jekyll-remote-theme

remote_theme: poole/lanyon
